title: Changho Shin
face: /assets/img/chshin.jpg
description: Postdoc at Princeton University
email: mailto:cs1095@princeton.edu
github: https://github.com/ch-shin
cv: https://ch-shin.github.io/assets/cv/cv_chshin_2602.pdf
twitter: https://twitter.com/Changho_Shin_
theme: jekyll-theme-minimal

header_pages:
  - index.md
  # - thoughts.md